ALTER TABLE DEPARTMENTREPLICA
ADD PRIMARY KEY(ID);

ALTER TABLE EMPLOYEEREPLICA
ADD FOREIGN KEY(DepartmentId) REFERENCES DEPARTMENTREPLICA(ID);



ALTER TABLE EMPLOYEEREPLICA 
  ADD CONSTRAINT fk_name 
  FOREIGN KEY (DepartmentId) 
  REFERENCES DEPARTMENTREPLICA(ID) 
  ON DELETE CASCADE;

  SELECT*FROM DEPARTMENTREPLICA;
  SELECT*FROM EMPLOYEEREPLICA;

  DELETE FROM DEPARTMENTREPLICA WHERE ID = 6;